Raiden1411/zabi

src/abi.zig, src/block.zig, src/client.zig, src/encoder.zig, src/meta/meta.zig
Introduces the base for the eth public client.
Adds the first public methods and performs some other minor changes to the UnionParser
=> feat: Introduces eth public client

src/client.zig
Added 3 more methods. `eth_gasPrice`, `eth_accounts`, `eth_chainId`.
=> feat: `eth_chainId`, `eth_gasPrice`, `eth_accounts`

src/client.zig
Adds transaction count methods via block hash or number.
=> feat: add 2 more client methods

src/client.zig
Improves the http client init. Also remove some d.r.y from implementation.
=> chore: update client init and remove some method repetition

src/rlp.zig
Introduces the RLP decode method, still needs more tests. Also fixes a couple of encode bugs.
=> feat: rlp decode

src/client.zig
Adds support for changing chainId.
=> feat: add support for changing chain

build.zig, build.zig.zon, pkg/libsecp256k1/build.zig, pkg/libsecp256k1/build.zig.zon, pkg/libsecp256k1/c.zig, pkg/libsecp256k1/root.zig, pkg/libsecp256k1/signature.zig, pkg/libsecp256k1/signer.zig, pkg/libsecp256k1/testing.zig, src/meta/transaction.zig, src/root.zig, src/serialize.zig
Adds libsecp256k1 with work for the wallet implementation.
Refactors build and adds new Envelope types.
=> feat: add libsecp256k1 support and starts wallet implementation

build.zig.zon, examples/watch/watch.zig, src/WebSocket.zig, src/meta/ethereum.zig, src/meta/meta.zig, src/meta/transaction.zig
=> fix: more client cleanup and fix bug with `r` and `s` values

examples/watch/build.zig, examples/watch/logs.zig, src/clients/WebSocket.zig, src/meta/json.zig, src/types/log.zig
Fixes a couple of lingering bugs on the websocket client and add a new example of usage.
=> websocket: fix bugs and introduce new example

build.zig, examples/contract/contract.zig, src/clients/Client.zig, src/clients/WebSocket.zig, src/clients/contract.zig, src/clients/wallet.zig, src/crypto/hdwallet.zig, src/utils/channel.zig
Increase the clients unit tests.
=> tests: increase clients tests

README.md, docs/pages/api/abi/constructor.md, docs/pages/api/abi/eip712.md, docs/pages/api/abi/error.md, docs/pages/api/abi/event.md, docs/pages/api/abi/function.md, docs/pages/api/abi/parameters.md, docs/pages/api/abi_utils/decode_constructor.md, docs/pages/api/abi_utils/decode_error.md, docs/pages/api/abi_utils/decode_function.md, docs/pages/api/abi_utils/decode_parameters.md, docs/pages/api/abi_utils/encode_constructor.md, docs/pages/api/abi_utils/encode_error.md, docs/pages/api/abi_utils/encode_function.md, docs/pages/api/abi_utils/encode_parameters.md, docs/pages/api/utilities/encoding/rlp_decode.md, docs/pages/api/utilities/encoding/rlp_encode.md, docs/pages/api/utilities/encoding/ssz_encode.md, docs/pages/api/utilities/signature/signer.md, docs/pages/api/utilities/transaction/parse.md, docs/pages/api/utilities/transaction/serialize.md, docs/pages/index.mdx, src/clients/wallet.zig, src/crypto/signature.zig
=> chore: fix typos

build.zig, src/clients/Client.zig, src/clients/WebSocket.zig, src/meta/json.zig, src/types/ethereum.zig, src/types/txpool.zig
Adds support for querying a nodes txpool.
=> txpool: add support for hitting txpool endpoints

build.zig, src/clients/IPC.zig, src/clients/ens/ens.zig, src/root.zig, src/tests/clients/ws_server.zig, src/ws_server.zig
Introduces a ws server similar to how the http server works for serving pseudo random data.
=> tests: add wsserver for generating random data

build.zig, src/ipc_server.zig, src/tests/clients/ipc_server.zig
Adds custom ipc server to generate random data.
=> server: add new ipc server to generate random data

README.md, docs/pages/index.mdx, examples/contract/contract.zig, examples/transfer/transfer.zig, examples/wallet/wallet.zig, examples/watch/logs.zig, examples/watch/watch.zig, src/abi/eip712.zig, src/clients/IPC.zig, src/clients/WebSocket.zig, src/clients/contract.zig, src/ipc_server.zig, src/rpc_server.zig, src/rpc_test.zig, src/tests/args.zig, src/types/ethereum.zig, src/types/transaction.zig, src/wallet_test.zig, src/ws_server.zig
Adds support for array and pointer types to args parser.
=> args: add more type support for args parser

.gitignore, README.md, src/clients/Client.zig, src/clients/IPC.zig, src/clients/WebSocket.zig, src/clients/contract.zig, src/clients/wallet.zig
Updates the pointer usage within the clients.
=> clients: update pointer usage within clients

docs/pages/api/client/block_explorer/explorer.md, docs/pages/api/interpreter/interpreter.md, docs/pages/api/utilities/transaction/serialize.md, docs/sidebar.ts, docs/vocs.config.tsx
Adds missing information to docs. More will soon be added.
=> docs: add interpreter and explorer to docs

src/clients/wallet.zig
Updates the internal transaction envelope pool search criteria to be more specific in what transaction is requested by nonce.
=> wallet: update transaction envelope pool search criteria

bench/BenchmarkType.zig, bench/benchmark.zig
This PR updates on the benchmark information is displayed. This is the first PR in updating the benchmarks.
=> bench: update how benchmarks are displayed

.github/workflows/benchmark.yml, .github/workflows/examples.yml, bench/benchmark.zig, bench/constants.zig, src/utils/utils.zig
This PR introduces more benchmark runners so that we can have a better idea how changes in the codebase affect performance.
Closes #80 
=> bench: add more benchmark runners

src/tests/Anvil.zig
This PR aims to add support for all `anvil` arguments and change on to start the child process.
=> anvil: rework on how to start the proccess and add all supported arguments

README.md, bench/benchmark.zig, docs/pages/index.mdx, examples/contract/contract.zig, examples/transfer/transfer.zig, examples/wallet/wallet.zig, examples/watch/logs.zig, examples/watch/watch.zig, src/clients/Client.zig, src/clients/IPC.zig, src/clients/WebSocket.zig, src/clients/contract.test.zig, src/clients/contract.zig, src/clients/ens/ens.test.zig, src/clients/ens/ens.zig, src/clients/ipc.test.zig, src/clients/optimism/clients/L1PubClient.zig, src/clients/optimism/clients/L1WalletClient.zig, src/clients/optimism/clients/L2PubClient.zig, src/clients/optimism/clients/L2WalletClient.zig, src/clients/optimism/clients/l1_public_client.test.zig, src/clients/optimism/clients/l2_public_client.test.zig, src/clients/public_client.test.zig, src/clients/wallet.test.zig, src/clients/wallet.zig, src/clients/websocket.test.zig
Updates the init method on the clients.
=> clients: update the `init` method on clients

build/docs_generate.zig, docs/pages/api/clients/contract.md, docs/pages/api/clients/multicall.md, docs/pages/api/clients/optimism/clients/L1PubClient.md, docs/pages/api/clients/optimism/clients/L1WalletClient.md, docs/pages/api/clients/optimism/clients/L2WalletClient.md, docs/pages/api/clients/wallet.md, docs/vocs.config.tsx, src/clients/wallet.zig, src/tests/clients/wallet.test.zig
Adds support for https://eips.ethereum.org/EIPS/eip-3074.
Closes #75
=> wallet: add support for eip3074 auth actions

build.zig, build.zig.zon, src/crypto/mnemonic.zig, src/tests/crypto/mnemonic.test.zig
=> crypto: add nfkd normalization to mnemonic wordlists

docs/pages/api/clients/Client.md, docs/pages/api/clients/wallet.md, docs/pages/api/crypto/mnemonic.md, docs/pages/api/decoding/parse_transaction.md, docs/pages/api/encoding/serialize.md, docs/pages/api/evm/opcodes.md, docs/pages/api/types/block.md, docs/pages/api/types/transaction.md, docs/pages/api/utils/env_load.md, docs/pages/api/utils/stack.md, src/clients/contract.zig, src/clients/wallet.zig, src/decoding/parse_transaction.zig, src/decoding/rlp_decode.zig, src/encoding/serialize.zig, src/types/explorer.zig, src/types/transaction.zig, src/utils/utils.zig, tests/clients/root.zig, tests/clients/wallet.test.zig, tests/decoding/parse_transaction.test.zig, tests/encoding/serialize.test.zig
Adds support for parts of https://eips.ethereum.org/EIPS/eip-7702
=> feat: add support for eip7702 transaction type and authorization utils

docs/pages/api/clients/Client.md, docs/pages/api/clients/IPC.md, docs/pages/api/clients/WebSocket.md, src/clients/Client.zig, src/clients/IPC.zig, src/clients/WebSocket.zig
What changes are made in this PR? Is it a feature or a bug fix?
=> chore: update docs

.github/workflows/main.yml, .github/workflows/pull-request.yml
What changes are made in this PR? Is it a feature or a bug fix?
=> chore: update ci runners

.github/workflows/examples.yml, bench/benchmark.zig, docs/pages/api/decoding/rlp_decode.md, docs/pages/api/utils/utils.md, src/clients/optimism/parse_deposit.zig, src/decoding/parse_transaction.zig, src/decoding/rlp_decode.zig, src/utils/utils.zig, tests/decoding/rlp_decode.test.zig
I wasn't happy with the current implementation of the RLP decoder so I restructured it.
=> decoder: refactor rlp implementation

build.zig, build.zig.zon, pkg/blst/build.zig.zon, pkg/c-kzg-4844/build.zig.zon, src/crypto/mnemonic.zig, src/encoding/logs.zig, tests/crypto/mnemonic.test.zig
=> chore: some library cleanup

README.md
=> docs: Update README.md for spelling mistakes

build.zig, examples/wasm/index.html, examples/wasm/main.js, src/evm/Interpreter.zig, src/evm/contract.zig, src/evm/instructions/arithmetic.zig, src/evm/instructions/contract.zig, src/evm/instructions/host.zig, src/evm/instructions/system.zig, src/evm/memory.zig, src/root_wasm.zig, src/wasm/evm.zig, src/wasm/utils.zig, tests/evm/interpreter.test.zig, tests/evm/system.test.zig
Add support for using our evm interpreter in wasm land.
=> wasm: make the evm interpreter compile to wasm

build/benchmark.zig, docs/pages/api/evm/opcodes.md, src/crypto/schnorr.zig, src/evm/opcodes.zig
=> chore: fix some typos in comment

.github/workflows/examples.yml, build.zig, examples/block_explorer/build.zig, examples/block_explorer/explorer.zig, examples/contract/build.zig, examples/contract/contract.zig, examples/interpreter/build.zig, examples/interpreter/interpreter.zig, examples/transfer/build.zig, examples/transfer/transfer.zig, examples/wallet/build.zig, examples/wallet/wallet.zig, examples/watch/build.zig, examples/watch/logs.zig, examples/watch/watch.zig
Check commit messages for more details but this adds a new command to build all examples.
=> build: add new examples build command

.github/CONTRIBUTING.md
Added the --ipc flag so that the IPC anvil instance is also started.
=> chore: more updates to CONTRIBUTING.md

src/ast/Ast.zig, src/ast/Parser.zig, src/clients/optimism/clients/L1PubClient.zig, tests/ast/parser.test.zig
Fixes #126. Check commit message for more details.
=> ast: allow parsing of multiple state modifiers

docs/package.json, examples/wasm/index_format.html, examples/wasm/main_format.js, pkg/blst/build.zig, src/ast/Ast.zig, src/ast/Parser.zig, src/ast/formatter.zig, src/clients/IPC.zig, src/clients/WebSocket.zig, src/root_wasm.zig, src/wasm/formatter.zig, src/wasm/wasm.zig, tests/ast/formatter.test.zig, tests/root_benchmark.zig
=> ast: extend support for the solidity formatter

build.zig, build.zig.zon, examples/autobahn/build.zig.zon, examples/block_explorer/build.zig.zon, examples/contract/build.zig.zon, examples/interpreter/build.zig.zon, examples/transfer/build.zig.zon, examples/wallet/build.zig.zon, examples/watch/build.zig.zon, pkg/blst/build.zig.zon, pkg/c-kzg-4844/build.zig, pkg/c-kzg-4844/build.zig.zon, src/ast/Ast.zig, src/ast/Parser.zig, src/ast/formatter.zig, src/clients/root.zig, src/clients/wallet.zig, src/encoding/serialize.zig, src/meta/json.zig, src/types/transaction.zig, tests/ast/formatter.test.zig, tests/root.zig, tests/root_benchmark.zig
What changes are made in this PR? Is it a feature or a bug fix?
=> ast: implement missing nodes for the formatter
